### ISSUE TITLE
4OP sound wrong.

### ISSUE THREAD

**Issue by denjhang** [danielrfry/opl2sd1#4] opened 2023-04-08 10:21 UTC
When I play some music that uses a true 4op sound, the sound becomes weird.

**Comment by denjhang** [comment] 2023-04-08 14:09
[Doukyusei_2_(IBM_PC).zip](https://github.com/danielrfry/opl2sd1/files/11183451/Doukyusei_2_.IBM_PC.zip)

**Comment by danielrfry** [comment] 2023-04-10 10:59
Audio files demonstrating the issue, for comparison:
[OPLSD1_Issue_4.zip](https://github.com/danielrfry/opl2sd1/files/11190036/OPLSD1_Issue_4.zip)

OPL3 version rendered using ymfm via `nsplay` from [Note Salad Tools](https://github.com/danielrfry/notesalad-tools)
YMF825 version played back using opl2sd1 firmware and [RetroWave_Player](https://github.com/SudoMaker/RetroWave) on macOS

**Comment by danielrfry** [comment] 2023-04-15 15:21
This was caused by some of the OPL 4-op connection modes not being mapped properly to their SD-1 equivalents, and is fixed in the latest build from main.

https://github.com/danielrfry/opl2sd1/actions/runs/4708450511

**Closed by danielrfry** 2023-04-15 15:21 UTC
